# Generated by Django 5.1 on 2026-02-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('title', models.CharField(blank=True, choices=[('أ.د', 'أ.د'), ('أ.م.د', 'أ.م.د'), ('دكتور', 'دكتور'), ('م. مساعد', 'م. مساعد'), ('مهندس', 'مهندس'), ('أخصائي', 'أخصائي'), ('فني', 'فني'), ('عامل/ خدمات', 'عامل/ خدمات'), ('دبلوم', 'دبلوم')], max_length=100, verbose_name='اللقب')),
                ('department', models.CharField(blank=True, choices=[('مفاعل الثاني', 'مفاعل الثاني'), ('مصنع الوقود النووي', 'مصنع الوقود النووي'), ('مصنع النظائر المشعة', 'مصنع النظائر المشعة'), ('مصنع اليورانيوم', 'مصنع اليورانيوم')], max_length=255, verbose_name='الجهة')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='الوظيفة')),
                ('course_type', models.CharField(blank=True, choices=[('دورة تدريبية', 'دورة تدريبية'), ('ورشة عمل', 'ورشة عمل'), ('فعالية', 'فعالية'), ('اجتماع فني', 'اجتماع فني'), ('المدرسة الروسية', 'المدرسة الروسية'), ('دورة مشتركة', 'دورة مشتركة')], max_length=100, verbose_name='نوع الدورة')),
                ('course_name', models.CharField(blank=True, max_length=500, verbose_name='اسم الدورة التدريبية')),
                ('course_location', models.CharField(blank=True, max_length=255, verbose_name='مكان إنعقاد الدورة')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='تاريخ من')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='تاريخ إلى')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='DadLine')),
                ('followup', models.CharField(blank=True, max_length=255, verbose_name='المتابعة')),
                ('attachment', models.FileField(blank=True, upload_to='attachments/%Y/%m/', verbose_name='المرفق')),
                ('event_code', models.CharField(blank=True, max_length=100, verbose_name='Event Code')),
                ('total_travels', models.CharField(blank=True, max_length=100, verbose_name='إجمالي سفريات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'سفرية',
                'verbose_name_plural': 'السفريات',
                'ordering': ['-created_at'],
            },
        ),
    ]
