# Generated by Django 5.1 on 2026-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
    ]
