# Generated by Django 5.1 on 2026-02-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travel_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم النوع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع السفرية',
                'verbose_name_plural': 'أنواع السفريات',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='travel',
            name='course_type',
            field=models.CharField(blank=True, choices=[('دورة تدريبية', 'دورة تدريبية'), ('ورشة عمل', 'ورشة عمل'), ('فعالية', 'فعالية'), ('اجتماع فني', 'اجتماع فني'), ('المدرسة الروسية', 'المدرسة الروسية'), ('دورة مشتركة', 'دورة مشتركة')], max_length=100, verbose_name='نوع الدورة (قديم)'),
        ),
        migrations.AddField(
            model_name='travel',
            name='travel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travels', to='travel.traveltype', verbose_name='نوع السفرية'),
        ),
    ]
