# Generated by Django 5.1 on 2026-02-16 11:48

from django.db import migrations


def migrate_course_types(apps, schema_editor):
    """Migrate existing course_type values to TravelType model."""
    Travel = apps.get_model('travel', 'Travel')
    TravelType = apps.get_model('travel', 'TravelType')

    # Get unique course_type values from existing data
    existing_types = Travel.objects.exclude(course_type='').values_list('course_type', flat=True).distinct()

    # Create TravelType records for each unique value
    type_mapping = {}
    for course_type_name in existing_types:
        travel_type, created = TravelType.objects.get_or_create(
            name=course_type_name,
            defaults={'is_active': True}
        )
        type_mapping[course_type_name] = travel_type

    # Update Travel records to reference TravelType
    for travel in Travel.objects.exclude(course_type=''):
        if travel.course_type in type_mapping:
            travel.travel_type = type_mapping[travel.course_type]
            travel.save(update_fields=['travel_type'])


def reverse_migration(apps, schema_editor):
    """For reversibility: copy travel_type.name back to course_type."""
    Travel = apps.get_model('travel', 'Travel')
    for travel in Travel.objects.filter(travel_type__isnull=False):
        travel.course_type = travel.travel_type.name
        travel.save(update_fields=['course_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_traveltype_alter_travel_course_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_course_types, reverse_migration),
    ]
