# Generated by Django 5.1 on 2026-02-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_migrate_course_type_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='aps',
            field=models.BooleanField(default=False, verbose_name='APS'),
        ),
        migrations.AddField(
            model_name='travel',
            name='publish_committee',
            field=models.BooleanField(default=False, verbose_name='لجنه النشر'),
        ),
        migrations.AddField(
            model_name='travel',
            name='sader',
            field=models.IntegerField(blank=True, null=True, verbose_name='صادر'),
        ),
        migrations.AddField(
            model_name='travel',
            name='visual_presentation',
            field=models.BooleanField(default=False, verbose_name='عرض مرئي'),
        ),
    ]
