# Generated by Django 5.1 on 2026-04-14 13:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الخطة')),
                ('lands_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='أراضي - بيان المشروع')),
                ('lands_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='أراضي - الخطة الأصلية')),
                ('lands_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='أراضي - الخطة المعدلة')),
                ('residential_buildings_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مباني سكنية - بيان المشروع')),
                ('residential_buildings_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مباني سكنية - الخطة الأصلية')),
                ('residential_buildings_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مباني سكنية - الخطة المعدلة')),
                ('non_residential_buildings_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مباني غير سكنية - بيان المشروع')),
                ('non_residential_buildings_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مباني غير سكنية - الخطة الأصلية')),
                ('non_residential_buildings_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مباني غير سكنية - الخطة المعدلة')),
                ('constructions_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تشييدات - بيان المشروع')),
                ('constructions_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تشييدات - الخطة الأصلية')),
                ('constructions_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تشييدات - الخطة المعدلة')),
                ('machinery_local_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='آلات محلي - بيان المشروع')),
                ('machinery_local_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='آلات محلي - الخطة الأصلية')),
                ('machinery_local_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='آلات محلي - الخطة المعدلة')),
                ('machinery_foreign_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='آلات أجنبي - بيان المشروع')),
                ('machinery_foreign_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='آلات أجنبي - الخطة الأصلية')),
                ('machinery_foreign_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='آلات أجنبي - الخطة المعدلة')),
                ('machinery_self_financed_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تمويل ذاتي - بيان المشروع')),
                ('machinery_self_financed_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تمويل ذاتي - الخطة الأصلية')),
                ('machinery_self_financed_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تمويل ذاتي - الخطة المعدلة')),
                ('transport_means_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='وسائل نقل - بيان المشروع')),
                ('transport_means_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='وسائل نقل - الخطة الأصلية')),
                ('transport_means_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='وسائل نقل - الخطة المعدلة')),
                ('furniture_equipment_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='أثاث وتجهيزات - بيان المشروع')),
                ('furniture_equipment_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='أثاث وتجهيزات - الخطة الأصلية')),
                ('furniture_equipment_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='أثاث وتجهيزات - الخطة المعدلة')),
                ('livestock_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='ثروة حيوانية - بيان المشروع')),
                ('livestock_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='ثروة حيوانية - الخطة الأصلية')),
                ('livestock_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='ثروة حيوانية - الخطة المعدلة')),
                ('transport_subtotal_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='جملة النقل والأثاث - بيان المشروع')),
                ('transport_subtotal_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='جملة النقل والأثاث - الخطة الأصلية')),
                ('transport_subtotal_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='جملة النقل والأثاث - الخطة المعدلة')),
                ('setup_preparations_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تجهيزات - بيان المشروع')),
                ('setup_preparations_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تجهيزات - الخطة الأصلية')),
                ('setup_preparations_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تجهيزات - الخطة المعدلة')),
                ('transport_travel_expenses_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='وسائل نقل وانتقال - بيان المشروع')),
                ('transport_travel_expenses_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='وسائل نقل وانتقال - الخطة الأصلية')),
                ('transport_travel_expenses_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='وسائل نقل وانتقال - الخطة المعدلة')),
                ('research_studies_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='أبحاث ودراسات - بيان المشروع')),
                ('research_studies_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='أبحاث ودراسات - الخطة الأصلية')),
                ('research_studies_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='أبحاث ودراسات - الخطة المعدلة')),
                ('setup_subtotal_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='جملة التجهيزات - بيان المشروع')),
                ('setup_subtotal_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='جملة التجهيزات - الخطة الأصلية')),
                ('setup_subtotal_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='جملة التجهيزات - الخطة المعدلة')),
                ('total_fixed_investment_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='جملة الاستثمار الثابت - بيان المشروع')),
                ('total_fixed_investment_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='جملة الاستثمار الثابت - الخطة الأصلية')),
                ('total_fixed_investment_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='جملة الاستثمار الثابت - الخطة المعدلة')),
                ('advance_payments_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='دفعات مقدمة واعتمادات مستندية - بيان المشروع')),
                ('advance_payments_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='دفعات مقدمة واعتمادات مستندية - الخطة الأصلية')),
                ('advance_payments_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='دفعات مقدمة واعتمادات مستندية - الخطة المعدلة')),
                ('grand_total_project', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='إجمالي الاستثمارات - بيان المشروع')),
                ('grand_total_original', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='إجمالي الاستثمارات - الخطة الأصلية')),
                ('grand_total_modified', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='إجمالي الاستثمارات - الخطة المعدلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'خطة استثمار',
                'verbose_name_plural': 'خطط الاستثمار',
                'ordering': ['-created_at'],
            },
        ),
    ]
