# Generated by Django 5.1 on 2026-04-14 22:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='manqool_ilaih_modified',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='منقول اليه - الخطة المعدلة'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='manqool_ilaih_original',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='منقول اليه - الخطة الأصلية'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='manqool_ilaih_project',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='منقول اليه - بيان المشروع'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='manqool_minh_modified',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='منقول منه - الخطة المعدلة'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='manqool_minh_original',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='منقول منه - الخطة الأصلية'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='manqool_minh_project',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='منقول منه - بيان المشروع'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='mutayyiqas_modified',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المتيقس - الخطة المعدلة'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='mutayyiqas_original',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المتيقس - الخطة الأصلية'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='mutayyiqas_project',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المتيقس - بيان المشروع'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='nisbat_munaffaz_modified',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='نسبه المنفذ - الخطة المعدلة'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='nisbat_munaffaz_original',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='نسبه المنفذ - الخطة الأصلية'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='nisbat_munaffaz_project',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='نسبه المنفذ - بيان المشروع'),
        ),
    ]
