# Generated by Django 5.1 on 2026-05-20 18:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_add_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManqoolMinhEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_field', models.CharField(choices=[('lands', 'أراضي (Lands)'), ('residential_buildings', 'مباني سكنية (Residential Buildings)'), ('non_residential_buildings', 'مباني غير سكنية (Non-residential Buildings)'), ('constructions', 'تشييدات (Constructions/Infrastructure)'), ('machinery_local', 'محلي (Local)'), ('machinery_foreign', 'أجنبي (Foreign)'), ('machinery_self_financed', 'تمويل ذاتي (Self-financed)'), ('transport_means', 'وسائل نقل (Means of Transport)'), ('furniture_equipment', 'أثاث وتجهيزات (Furniture & Equipment)'), ('livestock', 'ثروة حيوانية (Livestock)'), ('setup_preparations', 'تجهيزات (Setup/Technical Preparations)'), ('transport_travel_expenses', 'وسائل نقل وانتقال (Travel Expenses)'), ('research_studies', 'أبحاث ودراسات (Research & Studies)'), ('advance_payments', 'دفعات مقدمة (Advance Payments)')], max_length=64, verbose_name='الحقل المصدر')),
                ('main_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='القيمة الأساسية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manqool_minh_entries', to='investments.investmentplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'سجل منقول منه',
                'verbose_name_plural': 'سجلات منقول منه',
                'ordering': ['order', 'id'],
            },
        ),
    ]
