# Generated by Django 5.1 on 2026-05-20 19:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_manqoolminhentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='mutayyiqas_modified',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المتيقى - الخطة المعدلة'),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='mutayyiqas_original',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المتيقى - الخطة الأصلية'),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='mutayyiqas_project',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المتيقى - بيان المشروع'),
        ),
    ]
