# Generated by Django 5.1 on 2026-02-07 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=255, verbose_name='اسم مقدم الطلب')),
                ('job', models.CharField(blank=True, max_length=255, verbose_name='الوظيفة')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='المكان')),
                ('description', models.TextField(blank=True, verbose_name='البيان')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='القيمة التقديرية')),
                ('attachment', models.FileField(blank=True, upload_to='supplies/buy_orders/%Y/%m/', verbose_name='المرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'طلب شراء',
                'verbose_name_plural': 'طلبات الشراء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القناة')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='أنشئ بواسطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'قناة توريد',
                'verbose_name_plural': 'قنوات التوريد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('attachment', models.FileField(upload_to='supplies/offers/%Y/%m/', verbose_name='المرفق')),
                ('is_selected', models.BooleanField(default=False, verbose_name='مختار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='supplies.buyorder', verbose_name='طلب الشراء')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_order_no', models.CharField(blank=True, max_length=255, verbose_name='رقم أمر الخدمة')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('object_description', models.TextField(blank=True, verbose_name='الموضوع')),
                ('to_field', models.CharField(blank=True, max_length=255, verbose_name='إلى')),
                ('items', models.TextField(blank=True, verbose_name='البنود')),
                ('signature', models.CharField(blank=True, max_length=255, verbose_name='التوقيع')),
                ('attachment', models.FileField(blank=True, upload_to='supplies/service_orders/%Y/%m/', verbose_name='المرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='supplies.buyorder', verbose_name='طلب الشراء')),
            ],
            options={
                'verbose_name': 'أمر خدمة',
                'verbose_name_plural': 'أوامر الخدمة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='العنوان')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('attachment', models.FileField(blank=True, upload_to='supplies/posts/%Y/%m/', verbose_name='المرفق')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('supply_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='supplies.supplychannel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'منشور',
                'verbose_name_plural': 'المنشورات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='buyorder',
            name='supply_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_orders', to='supplies.supplychannel', verbose_name='القناة'),
        ),
    ]
