# Generated by Django 5.1 on 2026-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AddField(
            model_name='channelpost',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AddField(
            model_name='supplychannel',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
    ]
