# Generated by Django 5.1 on 2026-04-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_buyorder_is_accepted_channelpost_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='committee_financial',
            field=models.BooleanField(default=False, verbose_name='ش. مالية'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='committee_legal',
            field=models.BooleanField(default=False, verbose_name='ش. قانونية'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='committee_legal_signature',
            field=models.BooleanField(default=False, verbose_name='توقيع ش. قانونية'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='committee_supervisor_signature',
            field=models.BooleanField(default=False, verbose_name='توقيع المشرف'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='committee_technical',
            field=models.BooleanField(default=False, verbose_name='لجنة فنية'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='company_entity',
            field=models.CharField(blank=True, max_length=255, verbose_name='الشركة/الجهة'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='memo',
            field=models.FileField(blank=True, upload_to='supplies/buy_orders/memos/%Y/%m/', verbose_name='مذكرة'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='offer_divisible',
            field=models.BooleanField(default=False, verbose_name='عرض قابل للتجزئة'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='offer_envap',
            field=models.BooleanField(default=False, verbose_name='عرض Envap'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='offer_first',
            field=models.BooleanField(default=False, verbose_name='عرض أول'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='offer_second',
            field=models.BooleanField(default=False, verbose_name='عرض ثان'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='offer_third',
            field=models.BooleanField(default=False, verbose_name='عرض ثالث'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='supply_order_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='استخراج أمر التوريد رقم'),
        ),
    ]
