# Generated by Django 5.1 on 2026-04-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_buyorder_committee_financial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('supplies', 'توريدات'), ('maintenance', 'صيانة'), ('contracting', 'مقاولات')], max_length=20, verbose_name='نوع العملية')),
                ('operation_name', models.CharField(max_length=255, verbose_name='اسم العملية')),
                ('contracting_entity', models.CharField(blank=True, max_length=255, verbose_name='جهة التعاقد')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية التعاقد')),
                ('assignment_method', models.CharField(blank=True, choices=[('direct', 'أمر مباشر'), ('tender', 'مناقصة'), ('', '-')], max_length=20, verbose_name='طريقة الإسناد')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ الإجمالي')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ المدفوع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('attachment', models.FileField(blank=True, upload_to='supplies/contract_operations/%Y/%m/', verbose_name='المرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('supply_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_operations', to='supplies.supplychannel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'عملية تعاقد',
                'verbose_name_plural': 'عمليات التعاقد',
                'ordering': ['operation_type', '-created_at'],
            },
        ),
    ]
