# Generated by Django 5.1 on 2026-04-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_contractoperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='to_field',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='to_invap',
            field=models.CharField(blank=True, choices=[('', '-'), ('reactor', 'Al-Reactor / المفاعل'), ('fuel', 'Nuclear Fuel Factory / مصنع الوقود النووي'), ('isotopes', 'Radioactive Isotopes Factory / مصنع النظائر المشعة'), ('uranium', 'Uranium Factory / مصنع اليورانيو')], max_length=20, verbose_name='To INVAP'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='attachment',
            field=models.FileField(blank=True, upload_to='supplies/service_orders/%Y/%m/', verbose_name='attached'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='object_description',
            field=models.TextField(blank=True, verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_order_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='Service Order No'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='The signature'),
        ),
    ]
