# Generated by Django 5.1 on 2026-04-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_remove_serviceorder_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='to_invap',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='to_invap_fuel',
            field=models.BooleanField(default=False, verbose_name='Nuclear Fuel Factory / مصنع الوقود النووي'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='to_invap_isotopes',
            field=models.BooleanField(default=False, verbose_name='Radioactive Isotopes Factory / مصنع النظائر المشعة'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='to_invap_reactor',
            field=models.BooleanField(default=False, verbose_name='Al-Reactor / المفاعل'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='to_invap_uranium',
            field=models.BooleanField(default=False, verbose_name='Uranium Factory / مصنع اليورانيو'),
        ),
    ]
