# Generated by Django 5.1 on 2026-04-13 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_remove_serviceorder_to_invap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=255, verbose_name='الجهة')),
                ('supply_order_no', models.CharField(blank=True, max_length=255, verbose_name='رقم أمر التوريد')),
                ('amount_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ بالدولار')),
                ('amount_egyptian', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ بالمصري')),
                ('statement', models.TextField(blank=True, verbose_name='بيان')),
                ('supply_duration', models.CharField(blank=True, max_length=255, verbose_name='مدة التوريد')),
                ('amount_fully_disbursed', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ما تم صرفه بالكامل')),
                ('remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='الباقي')),
                ('not_disbursed_current_year', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ما لم يتم صرفه السنة الحالية')),
                ('prev_year_2020', models.BooleanField(default=False, verbose_name='2020')),
                ('prev_year_2021', models.BooleanField(default=False, verbose_name='2021')),
                ('prev_year_2022', models.BooleanField(default=False, verbose_name='2022')),
                ('prev_year_2023', models.BooleanField(default=False, verbose_name='2023')),
                ('prev_year_2024', models.BooleanField(default=False, verbose_name='2024')),
                ('prev_year_2025', models.BooleanField(default=False, verbose_name='2025')),
                ('prev_year_2026', models.BooleanField(default=False, verbose_name='2026')),
                ('attachment', models.FileField(blank=True, upload_to='supplies/ats_contracts/%Y/%m/', verbose_name='مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_contracts', to='supplies.buyorder', verbose_name='طلب الشراء')),
            ],
            options={
                'verbose_name': 'عقد ATS',
                'verbose_name_plural': 'عقود ATS',
                'ordering': ['-created_at'],
            },
        ),
    ]
