# Generated by Django 5.1 on 2026-04-13 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_atscontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_name', models.CharField(max_length=255, verbose_name='اسم المناقصة')),
                ('formal_inspection_minutes', models.BooleanField(default=False, verbose_name='محضر فحص شكلي')),
                ('admin_formation_order', models.BooleanField(default=False, verbose_name='بأمر إداري تشكيل')),
                ('technical_minutes', models.BooleanField(default=False, verbose_name='محضر فني')),
                ('minutes_1', models.BooleanField(default=False, verbose_name='محضر 1')),
                ('technical_report', models.BooleanField(default=False, verbose_name='تقرير فني')),
                ('minutes_2', models.BooleanField(default=False, verbose_name='محضر 2')),
                ('financial_opening', models.BooleanField(default=False, verbose_name='فتح مالي')),
                ('financial_report', models.BooleanField(default=False, verbose_name='تقرير مالي')),
                ('minutes_3', models.BooleanField(default=False, verbose_name='محضر 3')),
                ('bid_acceptance_notification', models.BooleanField(default=False, verbose_name='إخطار قبول العطاء')),
                ('attachment', models.FileField(blank=True, upload_to='supplies/tenders/%Y/%m/', verbose_name='مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('supply_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='supplies.supplychannel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'مناقصة',
                'verbose_name_plural': 'المناقصات',
                'ordering': ['-created_at'],
            },
        ),
    ]
