# Generated by Django 5.1 on 2026-05-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='envelope_opening_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/envelope_opening/%Y/%m/', verbose_name='مرفق محضر فض مظاريف'),
        ),
        migrations.AddField(
            model_name='tender',
            name='envelope_opening_minutes',
            field=models.BooleanField(default=False, verbose_name='محضر فض مظاريف'),
        ),
        migrations.AddField(
            model_name='tender',
            name='estimated_value_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/estimated_value/%Y/%m/', verbose_name='مرفق القيمة التقديرية'),
        ),
        migrations.AddField(
            model_name='tender',
            name='estimated_value_minutes',
            field=models.BooleanField(default=False, verbose_name='القيمة التقديرية'),
        ),
        migrations.AddField(
            model_name='tender',
            name='linking',
            field=models.BooleanField(default=False, verbose_name='ارتباط'),
        ),
        migrations.AddField(
            model_name='tender',
            name='linking_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/linking/%Y/%m/', verbose_name='مرفق الارتباط'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_type',
            field=models.CharField(blank=True, choices=[('limited', 'محدودة'), ('public', 'عامة')], max_length=20, verbose_name='مناقصات / مزايدات'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_type_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/tender_type/%Y/%m/', verbose_name='مرفق مناقصات / مزايدات'),
        ),
    ]
