# Generated by Django 5.1 on 2026-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_tender_envelope_opening_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='admin_formation_order_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/admin_formation/%Y/%m/', verbose_name='مرفق بأمر إداري تشكيل'),
        ),
        migrations.AddField(
            model_name='tender',
            name='bid_acceptance_notification_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/bid_acceptance/%Y/%m/', verbose_name='مرفق إخطار قبول العطاء'),
        ),
        migrations.AddField(
            model_name='tender',
            name='financial_opening_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/financial_opening/%Y/%m/', verbose_name='مرفق فتح مالي'),
        ),
        migrations.AddField(
            model_name='tender',
            name='financial_report_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/financial_report/%Y/%m/', verbose_name='مرفق تقرير مالي'),
        ),
        migrations.AddField(
            model_name='tender',
            name='formal_inspection_minutes_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/formal_inspection/%Y/%m/', verbose_name='مرفق محضر فحص شكلي'),
        ),
        migrations.AddField(
            model_name='tender',
            name='minutes_1_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/minutes_1/%Y/%m/', verbose_name='مرفق محضر 1'),
        ),
        migrations.AddField(
            model_name='tender',
            name='minutes_2_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/minutes_2/%Y/%m/', verbose_name='مرفق محضر 2'),
        ),
        migrations.AddField(
            model_name='tender',
            name='minutes_3_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/minutes_3/%Y/%m/', verbose_name='مرفق محضر 3'),
        ),
        migrations.AddField(
            model_name='tender',
            name='technical_minutes_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/technical_minutes/%Y/%m/', verbose_name='مرفق محضر فني'),
        ),
        migrations.AddField(
            model_name='tender',
            name='technical_report_attachment',
            field=models.FileField(blank=True, upload_to='supplies/tenders/technical_report/%Y/%m/', verbose_name='مرفق تقرير فني'),
        ),
    ]
