# Generated by Django 5.1 on 2026-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_tender_admin_formation_order_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='tender_name',
            field=models.CharField(max_length=1000, verbose_name='اسم المناقصة'),
        ),
    ]
