# Generated by Django 5.1 on 2026-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0011_alter_tender_tender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='estimated_value_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة القيمة التقديرية (%)'),
        ),
    ]
