# Generated by Django 5.1 on 2026-05-20 19:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الميزانية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'ميزانية',
                'verbose_name_plural': 'الميزانيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveSmallIntegerField(choices=[(1, 'باب 1'), (2, 'باب 2'), (3, 'باب 3'), (4, 'باب 4'), (5, 'باب 5'), (6, 'باب 6')], verbose_name='رقم الباب')),
                ('allocated', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المبلغ الموزع')),
                ('reinforcement', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='تعزيز')),
                ('commitment', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='ارتباط')),
                ('expenditure', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='صرف')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='budgets.budget', verbose_name='الميزانية')),
            ],
            options={
                'verbose_name': 'باب ميزانية',
                'verbose_name_plural': 'أبواب الميزانية',
                'ordering': ['chapter_number'],
                'unique_together': {('budget', 'chapter_number')},
            },
        ),
    ]
