# Generated by Django 5.1 on 2026-02-07 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القناة')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='أنشئ بواسطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'قناة',
                'verbose_name_plural': 'القنوات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_name', models.CharField(max_length=255, verbose_name='اسم المفتش')),
                ('job', models.CharField(blank=True, max_length=255, verbose_name='الوظيفة')),
                ('authority', models.CharField(blank=True, choices=[('تفتيش الوكالة', 'تفتيش الوكالة'), ('تفتيش هيئة الرقابة النووية والإشعاعية', 'تفتيش هيئة الرقابة النووية والإشعاعية')], max_length=255, verbose_name='جهة التفتيش')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الزيارة')),
                ('result', models.CharField(blank=True, choices=[('استيفاء متطلبات', 'استيفاء متطلبات'), ('ملاحظات', 'ملاحظات'), ('توصيات', 'توصيات'), ('اشتراطات', 'اشتراطات'), ('تقرير', 'تقرير'), ('إجراءات تصحيحية', 'إجراءات تصحيحية')], max_length=255, verbose_name='النتيجة')),
                ('attachment', models.FileField(blank=True, upload_to='licenses/inspection/%Y/%m/', verbose_name='المرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='licenses.channel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'تفتيش',
                'verbose_name_plural': 'التفتيشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255, verbose_name='اسم المتقدم')),
                ('category', models.CharField(blank=True, choices=[('خبير وقاية', 'خبير وقاية'), ('مستخدم', 'مستخدم'), ('فني', 'فني'), ('مساعد فني', 'مساعد فني')], max_length=100, verbose_name='الفئة')),
                ('job', models.CharField(blank=True, max_length=255, verbose_name='الوظيفة')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('license_type', models.CharField(blank=True, choices=[('جديد', 'جديد'), ('تجديد', 'تجديد'), ('تعديل', 'تعديل')], max_length=100, verbose_name='نوع الترخيص')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='تاريخ من')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='تاريخ إلى')),
                ('license_duration', models.CharField(blank=True, choices=[('شهر', 'شهر'), ('سنة', 'سنة'), ('سنتين', 'سنتين'), ('3 سنوات', '3 سنوات')], max_length=100, verbose_name='مدة الترخيص')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم السداد')),
                ('attachment', models.FileField(blank=True, upload_to='licenses/personal/%Y/%m/', verbose_name='المرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_licenses', to='licenses.channel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'ترخيص شخصي',
                'verbose_name_plural': 'التراخيص الشخصية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_duration', models.CharField(blank=True, max_length=255, verbose_name='مدة الترخيص')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='تاريخ من')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='تاريخ إلى')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم السداد')),
                ('attachment', models.FileField(blank=True, upload_to='licenses/place/%Y/%m/', verbose_name='المرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_licenses', to='licenses.channel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'ترخيص مكاني',
                'verbose_name_plural': 'التراخيص المكانية',
                'ordering': ['-created_at'],
            },
        ),
    ]
