# Generated by Django 5.1 on 2026-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AddField(
            model_name='personallicense',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AddField(
            model_name='placelicense',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
    ]
